<?php

namespace Tests;

use App\Models\AppSetting;
use App\Models\JenisTagihan;
use App\Models\Kategori;
use App\Models\Kelas;
use App\Models\Pembayaran;
use App\Models\Pengeluaran;
use App\Models\Siswa;
use App\Models\Tagihan;
use App\Models\User;
use App\Models\Wali;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\DB;


abstract class TestCase extends BaseTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete('delete from users');
        DB::delete('delete from pembayarans');
        DB::delete('delete from tagihans');
        DB::delete('delete from jenis_tagihans');
        DB::delete('delete from pengeluarans');
        DB::delete('delete from siswas');
        DB::delete('delete from kelas');
        DB::delete('delete from kategoris');
        DB::delete('delete from walis');
    }

    /**
     * Skenario dasar untuk admin dan satu siswa MI lengkap relasi.
     */
    protected function createSiswaMiScenario(): array
    {
        $admin = User::factory()->admin()->create();

        $ayah = Wali::factory()->create();
        $ibu = Wali::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();

        $siswa = Siswa::factory()->create([
            'tanggal_lahir' => '2000-01-01',
            'jenjang' => 'MI',
            'ayah_id' => $ayah->id,
            'ibu_id' => $ibu->id,
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);

        return compact('admin', 'ayah', 'ibu', 'wali', 'kelas', 'kategori', 'siswa');
    }

    protected function createSiswaTkScenario(): array
    {
        $admin = User::factory()->admin()->create();

        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();

        $siswa = Siswa::factory()->create([
            'jenjang' => 'TK',
            'ayah_id' => null,
            'ibu_id' => null,
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);

        return compact('admin', 'wali', 'kelas', 'kategori', 'siswa');
    }

    protected function createSiswaKbScenario(): array
    {
        $admin = User::factory()->admin()->create();

        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();

        $siswa = Siswa::factory()->create([
            'jenjang' => 'KB',
            'ayah_id' => null,
            'ibu_id' => null,
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);

        return compact('admin', 'wali', 'kelas', 'kategori', 'siswa');
    }

    protected function createPembayaranCicil()
    {
        $user = User::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP',
            'jumlah' => 100000
        ]);
        $siswa = Siswa::factory()
            ->for($wali, 'ayah')
            ->for($wali, 'ibu')
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create([
                'jenjang' => 'MI'
            ]);
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create([
                'tmp' => 100000,
                'status' => 'Lunas'
            ]);
        $pembayaran = Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'jumlah' => 50000,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        $setting = AppSetting::factory()->create();
        return compact('user', 'pembayaran');
    }
    protected function createPembayaranLunas()
    {
        $user = User::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP',
            'jumlah' => 100000
        ]);
        $siswa = Siswa::factory()
            ->for($wali, 'ayah')
            ->for($wali, 'ibu')
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create([
                'jenjang' => 'MI'
            ]);
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create();
        $pembayaran = Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'jumlah' => $jt->jumlah,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        $setting = AppSetting::factory()->create();
        return compact('user', 'pembayaran');
    }
    protected function createTagihan()
    {
        $user = User::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'Pendaftaran',
            'jumlah' => 50000
        ]);
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $wali = Wali::factory()->create();
        $siswa = Siswa::factory()
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create();
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create();
        return compact('user', 'tagihan');
    }
    protected function createKasHarian()
    {
        $user = User::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP',
            'jumlah' => 100000
        ]);
        $siswa = Siswa::factory()
            ->for($wali, 'ayah')
            ->for($wali, 'ibu')
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create([
                'jenjang' => 'MI'
            ]);
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create();
        // Pemasukan & Pengeluaran dalam bulan Januari 2025
        Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'tanggal' => '2025-01-01',
                'jumlah' => $jt->jumlah,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        // Tambahan pemasukan di Januari
        Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'tanggal' => '2025-01-10',
                'jumlah' => 50000,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        // Pemasukan di bulan lain (Februari) — memastikan tidak mempengaruhi saldo Januari
        Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'tanggal' => '2025-02-01',
                'jumlah' => $jt->jumlah,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        Pengeluaran::factory()->create([
            'tanggal' => '2025-01-01',
            'jumlah' => 50000,
        ]);
        // Pengeluaran tambahan di Januari
        Pengeluaran::factory()->create([
            'tanggal' => '2025-01-05',
            'jumlah' => 25000,
        ]);
        return compact('user');
    }

    protected function createKasHarianWithPrevMonth()
    {
        $user = \App\Models\User::factory()->create();
        // Bulan sebelumnya (Desember 2024)
        $wali = \App\Models\Wali::factory()->create();
        $kelas = \App\Models\Kelas::factory()->create();
        $kategori = \App\Models\Kategori::factory()->create();
        $jt = \App\Models\JenisTagihan::factory()->create(['nama'=>'SPP','jumlah'=>100000]);
        $siswa = \App\Models\Siswa::factory()
            ->for($wali,'wali')
            ->for($kelas,'kelas')
            ->for($kategori,'kategori')
            ->create(['jenjang'=>'MI']);
        $tagihan = \App\Models\Tagihan::factory()->for($siswa,'siswa')->for($jt,'jenis_tagihan')->create();
        // Transaksi bulan sebelumnya
        \App\Models\Pembayaran::factory()->for($tagihan,'tagihan')->create([
            'tanggal' => '2024-12-15',
            'jumlah' => 75000,
            'metode' => 'Tunai'
        ]);
        \App\Models\Pengeluaran::factory()->create([
            'tanggal' => '2024-12-20',
            'jumlah' => 25000
        ]);
        // Transaksi bulan target (Januari 2025)
        \App\Models\Pembayaran::factory()->for($tagihan,'tagihan')->create([
            'tanggal' => '2025-01-05',
            'jumlah' => 50000,
            'metode' => 'Tunai'
        ]);
        \App\Models\Pengeluaran::factory()->create([
            'tanggal' => '2025-01-10',
            'jumlah' => 10000
        ]);
        return compact('user');
    }

    protected function createRekapBulanan()
    {
        $user = User::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP',
            'jumlah' => 100000
        ]);
        $siswa = Siswa::factory()
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create([
                'jenjang' => 'MI'
            ]);
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create();

        // Pemasukan Jan & Feb
        Pembayaran::factory()->for($tagihan, 'tagihan')->create([
            'tanggal' => '2025-01-01',
            'jumlah' => 100000,
            'metode' => 'Tunai'
        ]);
        Pembayaran::factory()->for($tagihan, 'tagihan')->create([
            'tanggal' => '2025-02-01',
            'jumlah' => 150000,
            'metode' => 'Tunai'
        ]);

        // Pengeluaran Jan & Feb
        Pengeluaran::factory()->create([
            'tanggal' => '2025-01-15',
            'jumlah' => 40000,
        ]);
        Pengeluaran::factory()->create([
            'tanggal' => '2025-02-10',
            'jumlah' => 50000,
        ]);
        Pengeluaran::factory()->create([
            'tanggal' => '2026-01-01',
            'jumlah' => 10000,
        ]);

        return compact('user');
    }

    protected function createRekapBulananWithPrevYear()
    {
        $user = \App\Models\User::factory()->create();
        $wali = \App\Models\Wali::factory()->create();
        $kelas = \App\Models\Kelas::factory()->create();
        $kategori = \App\Models\Kategori::factory()->create();
        $jt = \App\Models\JenisTagihan::factory()->create(['nama'=>'SPP','jumlah'=>100000]);
        $siswa = \App\Models\Siswa::factory()->for($wali,'wali')->for($kelas,'kelas')->for($kategori,'kategori')->create(['jenjang'=>'MI']);
        $tagihan = \App\Models\Tagihan::factory()->for($siswa,'siswa')->for($jt,'jenis_tagihan')->create();
        // Tahun sebelumnya (2024)
        \App\Models\Pembayaran::factory()->for($tagihan,'tagihan')->create([
            'tanggal'=>'2024-11-01',
            'jumlah'=>60000,
            'metode'=>'Tunai'
        ]);
        \App\Models\Pengeluaran::factory()->create([
            'tanggal'=>'2024-12-01',
            'jumlah'=>15000
        ]);
        // Tahun target (2025) beberapa bulan
        \App\Models\Pembayaran::factory()->for($tagihan,'tagihan')->create([
            'tanggal'=>'2025-01-10',
            'jumlah'=>50000,
            'metode'=>'Tunai'
        ]);
        \App\Models\Pembayaran::factory()->for($tagihan,'tagihan')->create([
            'tanggal'=>'2025-02-05',
            'jumlah'=>40000,
            'metode'=>'Tunai'
        ]);
        \App\Models\Pengeluaran::factory()->create([
            'tanggal'=>'2025-02-15',
            'jumlah'=>10000
        ]);
        return compact('user');
    }

    protected function createAdminWithToken(): \App\Models\User
    {
        /** @var \App\Models\User $admin */
        $admin = \App\Models\User::factory()->admin()->create();
        $admin->token = \Illuminate\Support\Str::uuid()->toString();
        $admin->save();

        return $admin;
    }

    // --- Wali scenarios & payload builders ---
    protected function createWaliIndexScenario(int $count = 3): array
    {
        $user = \App\Models\User::factory()->create();
        \App\Models\Wali::factory()->count($count)->create();
        return compact('user');
    }

    protected function createWaliSearchScenario(): array
    {
        $user = \App\Models\User::factory()->create();
        \App\Models\Wali::factory()->create(['nama' => 'Budi Santoso']);
        \App\Models\Wali::factory()->create(['nama' => 'Andi Wijaya']);
        return compact('user');
    }

    protected function createWaliForCrud(): array
    {
        $user = \App\Models\User::factory()->create();
        $wali = \App\Models\Wali::factory()->create();
        $siswa = \App\Models\Siswa::factory()->create([
            'wali_id' => $wali->id,
        ]);
        return compact('user', 'wali');
    }

    protected function buildWaliValidPayload(): array
    {
        return [
            'nama' => 'Ayah',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Islam',
            'pendidikan_terakhir' => 'SMA',
            'pekerjaan' => 'Wiraswasta',
            'alamat' => 'Pontianak',
            'no_hp' => '081122334455',
            'keterangan' => null,
        ];
    }

    protected function buildWaliInvalidRequiredPayload(): array
    {
        return [];
    }

    protected function buildWaliInvalidJenisKelaminPayload(): array
    {
        $p = $this->buildWaliValidPayload();
        $p['jenis_kelamin'] = 'Unknown';
        return $p;
    }

    protected function buildWaliInvalidNoHpPayload(): array
    {
        $p = $this->buildWaliValidPayload();
        $p['no_hp'] = 'invalid#phone';
        return $p;
    }

    // --- Kelas scenarios & payload builders ---
    protected function createKelasIndexScenario(string $jenjang = 'MI', int $count = 3): array
    {
        $user = User::factory()->create();
        Kelas::factory()->count($count)->create([
            'jenjang' => $jenjang,
        ]);
        return compact('user');
    }

    protected function createKelasCrudScenario(string $jenjang = 'MI'): array
    {
        $user = User::factory()->create();
        $kelas = Kelas::factory()->create([
            'jenjang' => $jenjang,
            'nama' => 'KELAS 1'
        ]);
        return compact('user', 'kelas');
    }

    protected function createKelasWithSiswaScenario(string $jenjang = 'MI'): array
    {
        $user = User::factory()->create();
        $kelas = Kelas::factory()->create([
            'jenjang' => $jenjang,
        ]);
        $wali = Wali::factory()->create();
        $kategori = Kategori::factory()->create();
        Siswa::factory()->create([
            'jenjang' => $jenjang,
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);
        return compact('user', 'kelas');
    }

    protected function buildKelasValidPayload(): array
    {
        return [
            'nama' => 'Kelas 2'
        ];
    }

    protected function buildKelasInvalidPayloadMissingNama(): array
    {
        return [];
    }

    protected function buildKelasInvalidPayloadLongNama(): array
    {
        return [
            'nama' => str_repeat('A', 101)
        ];
    }

    protected function buildKelasDuplicatePayload(string $existingName): array
    {
        return [
            'nama' => $existingName
        ];
    }

    // --- Kategori scenarios & payload builders ---
    protected function createKategoriIndexScenario(int $count = 3): array
    {
        $user = User::factory()->create();
        Kategori::factory()->count($count)->create();
        return compact('user');
    }

    protected function createKategoriCrudScenario(): array
    {
        $user = User::factory()->create();
        $kategori = Kategori::factory()->create(['nama' => 'BERSAUDARA']);
        return compact('user', 'kategori');
    }
    protected function createKategoriWithSiswaScenario(): array
    {
        $user = User::factory()->create();
        $kategori = Kategori::factory()->create(['nama' => 'YATIM']);
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create(['jenjang' => 'MI']);
        Siswa::factory()->create([
            'jenjang' => 'MI',
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id
        ]);
        return compact('user', 'kategori');
    }

    protected function buildKategoriValidPayload(): array
    {
        return ['nama' => 'BERSAUDARA'];
    }

    protected function buildKategoriInvalidMissingNamaPayload(): array
    {
        return [];
    }

    protected function buildKategoriInvalidLongNamaPayload(): array
    {
        return ['nama' => str_repeat('A', 101)];
    }

    protected function buildKategoriDuplicatePayload(string $existingName): array
    {
        return ['nama' => $existingName];
    }

    // Jenis Tagihan helpers
    protected function createJenisTagihanIndexScenario(int $count = 3): array
    {
        $user = User::factory()->admin()->create();
        $user->token = 'token-index';
        $user->save();
        JenisTagihan::factory()->count($count)->create();
        return compact('user');
    }

    protected function createJenisTagihanCrudScenario(): array
    {
        $user = User::factory()->admin()->create();
        $user->token = 'token-crud';
        $user->save();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP JANUARI',
            'jumlah' => 75000,
        ]);
        return compact('user','jt');
    }

    protected function createJenisTagihanWithTagihanScenario(): array
    {
        $user = User::factory()->admin()->create();
        $user->token = 'token-relasi';
        $user->save();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'PENDAFTARAN',
            'jumlah' => 100000,
        ]);
        $siswa = Siswa::factory()->create();
        Tagihan::factory()->create([
            'jenis_tagihan_id' => $jt->id,
            'nis' => $siswa->nis,
        ]);
        return compact('user','jt');
    }

    protected function buildJenisTagihanValidPayload(): array
    {
        return [
            'nama' => 'SPP FEBRUARI',
            'jatuh_tempo' => now()->addDay()->format('Y-m-d'),
            'jumlah' => 85000.50,
        ];
    }

    protected function buildJenisTagihanInvalidRequiredPayload(): array
    {
        return [];
    }

    protected function buildJenisTagihanInvalidNamaShort(): array
    {
        $p = $this->buildJenisTagihanValidPayload();
        $p['nama'] = 'A';
        return $p;
    }

    protected function buildJenisTagihanInvalidNamaLong(): array
    {
        $p = $this->buildJenisTagihanValidPayload();
        $p['nama'] = str_repeat('X', 101);
        return $p;
    }

    protected function buildJenisTagihanInvalidJatuhTempoFormat(): array
    {
        $p = $this->buildJenisTagihanValidPayload();
        $p['jatuh_tempo'] = '31-12-2025';
        return $p;
    }

    protected function buildJenisTagihanInvalidJumlahNonNumeric(): array
    {
        $p = $this->buildJenisTagihanValidPayload();
        $p['jumlah'] = 'ABC';
        return $p;
    }

    protected function buildJenisTagihanInvalidJumlahTooLong(): array
    {
        $p = $this->buildJenisTagihanValidPayload();
        $p['jumlah'] = '1234567890123.00';
        return $p;
    }

    // ===== Tagihan Scenarios =====
    protected function createTagihanIndexScenario(int $count = 3): array
    {
        $admin = \App\Models\User::factory()->admin()->create(['token' => 'tagihan-index']);
        $jt = \App\Models\JenisTagihan::factory()->create();
        $kelas = \App\Models\Kelas::factory()->create();
        $kategori = \App\Models\Kategori::factory()->create();
        $wali = \App\Models\Wali::factory()->create();
        $siswa = \App\Models\Siswa::factory()->count($count)->create([
            'jenjang' => 'MI',
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);
        foreach ($siswa as $s) {
            \App\Models\Tagihan::factory()->create([
                'jenis_tagihan_id' => $jt->id,
                'nis' => $s->nis,
            ]);
        }
        return compact('admin','jt','kelas','kategori','wali','siswa');
    }
    protected function createTagihanMassScenario(int $count = 3): array
    {
        $admin = \App\Models\User::factory()->admin()->create(['token' => 'tagihan-index']);
        $jt = \App\Models\JenisTagihan::factory()->create();
        $kelas = \App\Models\Kelas::factory()->create();
        $kategori = \App\Models\Kategori::factory()->create();
        $wali = \App\Models\Wali::factory()->create();
        $siswa = \App\Models\Siswa::factory()->count($count)->create([
            'jenjang' => 'MI',
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);
        return compact('admin','jt','kelas','kategori','wali','siswa');
    }

    protected function createTagihanEmptyScenario(): array
    {
        $admin = \App\Models\User::factory()->admin()->create(['token' => 'tagihan-empty']);
        return compact('admin');
    }

    protected function createTagihanSearchScenario(): array
    {
        $admin = \App\Models\User::factory()->admin()->create(['token' => 'tagihan-search']);
        $jt = \App\Models\JenisTagihan::factory()->create(['nama' => 'SPP']);
        $kelas = \App\Models\Kelas::factory()->create();
        $kategori = \App\Models\Kategori::factory()->create();
        $wali = \App\Models\Wali::factory()->create();
        $targetSiswa = \App\Models\Siswa::factory()->create([
            'nama' => 'Adi Nugroho',
            'jenjang' => 'MI',
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);
        $otherSiswa = \App\Models\Siswa::factory()->create([
            'nama' => 'Budi',
            'jenjang' => 'MI',
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);
        $tagihanTarget = \App\Models\Tagihan::factory()->create([
            'jenis_tagihan_id' => $jt->id,
            'nis' => $targetSiswa->nis,
        ]);
        $tagihanOther = \App\Models\Tagihan::factory()->create([
            'jenis_tagihan_id' => $jt->id,
            'nis' => $otherSiswa->nis,
        ]);
        return compact('admin','jt','kelas','kategori','wali','targetSiswa','otherSiswa','tagihanTarget','tagihanOther');
    }

    protected function createTagihanCrudScenario(): array
    {
        $admin = \App\Models\User::factory()->admin()->create(['token' => 'tagihan-crud']);
        $jt = \App\Models\JenisTagihan::factory()->create(['nama' => 'Pendaftaran', 'jumlah' => 50000]);
        $kelas = \App\Models\Kelas::factory()->create();
        $kategori = \App\Models\Kategori::factory()->create();
        $wali = \App\Models\Wali::factory()->create();
        $siswa = \App\Models\Siswa::factory()->create([
            'jenjang' => 'MI',
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);
        $tagihan = \App\Models\Tagihan::factory()->create([
            'jenis_tagihan_id' => $jt->id,
            'nis' => $siswa->nis,
        ]);
        return compact('admin','jt','kelas','kategori','wali','siswa','tagihan');
    }

    protected function createTagihanWithPembayaranScenario(): array
    {
        $admin = \App\Models\User::factory()->admin()->create(['token' => 'tagihan-pembayaran']);
        $jt = \App\Models\JenisTagihan::factory()->create(['nama' => 'SPP', 'jumlah' => 100000]);
        $siswa = \App\Models\Siswa::factory()->create(['jenjang' => 'MI']);
        $tagihan = \App\Models\Tagihan::factory()->create([
            'jenis_tagihan_id' => $jt->id,
            'nis' => $siswa->nis,
            'tmp' => 100000,
            'status' => 'Lunas'
        ]);
        \App\Models\Pembayaran::factory()->create([
            'kode_tagihan' => $tagihan->kode_tagihan,
            'jumlah' => 100000,
            'metode' => 'Tunai'
        ]);
        return compact('admin','jt','siswa','tagihan');
    }

    protected function buildTagihanValidPayload(array $overrides = []): array
    {
        $jt = $overrides['jt'] ?? \App\Models\JenisTagihan::factory()->create();
        $kelas = $overrides['kelas'] ?? \App\Models\Kelas::factory()->create();
        $kategori = $overrides['kategori'] ?? \App\Models\Kategori::factory()->create();
        return [
            'jenis_tagihan_id' => $jt->id,
            'jenjang' => 'MI',
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ];
    }

    protected function buildTagihanInvalidRequiredPayload(): array
    {
        return [];
    }

    protected function buildTagihanInvalidJenjangPayload(): array
    {
        $p = $this->buildTagihanValidPayload();
        $p['jenjang'] = 'INVALID';
        return $p;
    }

    protected function buildTagihanInvalidRelasiPayload(): array
    {
        return [
            'jenis_tagihan_id' => 999999,
            'jenjang' => 'MI',
            'kelas_id' => 999999,
            'kategori_id' => 999999,
        ];
    }
}
