<?php

namespace Tests;

use App\Models\AppSetting;
use App\Models\JenisTagihan;
use App\Models\Kategori;
use App\Models\Kelas;
use App\Models\Pembayaran;
use App\Models\Siswa;
use App\Models\Tagihan;
use App\Models\User;
use App\Models\Wali;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\DB;


abstract class TestCase extends BaseTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete('delete from siswas');
        DB::delete('delete from users');
        DB::delete('delete from kategoris');
        DB::delete('delete from kelas');
        DB::delete('delete from walis');
        DB::delete('delete from tagihans');
        DB::delete('delete from jenis_tagihans');
        DB::delete('delete from pembayarans');
    }

    /**
     * Skenario dasar untuk admin dan satu siswa MI lengkap relasi.
     */
    protected function createSiswaMiScenario(): array
    {
        $admin = User::factory()->admin()->create();

        $ayah = Wali::factory()->create();
        $ibu = Wali::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();

        $siswa = Siswa::factory()->create([
            'tanggal_lahir' => '2000-01-01',
            'jenjang' => 'MI',
            'ayah_id' => $ayah->id,
            'ibu_id' => $ibu->id,
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);

        return compact('admin', 'ayah', 'ibu', 'wali', 'kelas', 'kategori', 'siswa');
    }

    protected function createSiswaTkScenario(): array
    {
        $admin = User::factory()->admin()->create();

        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();

        $siswa = Siswa::factory()->create([
            'jenjang' => 'TK',
            'ayah_id' => null,
            'ibu_id' => null,
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);

        return compact('admin', 'wali', 'kelas', 'kategori', 'siswa');
    }

    protected function createSiswaKbScenario(): array
    {
        $admin = User::factory()->admin()->create();

        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();

        $siswa = Siswa::factory()->create([
            'jenjang' => 'KB',
            'ayah_id' => null,
            'ibu_id' => null,
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);

        return compact('admin', 'wali', 'kelas', 'kategori', 'siswa');
    }

    protected function createPembayaranCicil()
    {
        $user = User::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP',
            'jumlah' => 100000
        ]);
        $siswa = Siswa::factory()
            ->for($wali, 'ayah')
            ->for($wali, 'ibu')
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create([
                'jenjang' => 'MI'
            ]);
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create([
                'tmp' => 150000,
                'status' => 'Lunas'
            ]);
        $pembayaran = Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'jumlah' => 50000,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        $setting = AppSetting::factory()->create();
        return compact('user', 'pembayaran');
    }
    protected function createPembayaranLunas()
    {
        $user = User::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP',
            'jumlah' => 100000
        ]);
        $siswa = Siswa::factory()
            ->for($wali, 'ayah')
            ->for($wali, 'ibu')
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create([
                'jenjang' => 'MI'
            ]);
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create();
        $pembayaran = Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'jumlah' => $jt->jumlah,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        $setting = AppSetting::factory()->create();
        return compact('user', 'pembayaran');
    }
}
