<?php

namespace Tests;

use App\Models\AppSetting;
use App\Models\JenisTagihan;
use App\Models\Kategori;
use App\Models\Kelas;
use App\Models\Pembayaran;
use App\Models\Pengeluaran;
use App\Models\Siswa;
use App\Models\Tagihan;
use App\Models\User;
use App\Models\Wali;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\DB;


abstract class TestCase extends BaseTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete('delete from siswas');
        DB::delete('delete from users');
        DB::delete('delete from kategoris');
        DB::delete('delete from kelas');
        DB::delete('delete from walis');
        DB::delete('delete from tagihans');
        DB::delete('delete from jenis_tagihans');
        DB::delete('delete from pembayarans');
        DB::delete('delete from pengeluarans');
    }

    /**
     * Skenario dasar untuk admin dan satu siswa MI lengkap relasi.
     */
    protected function createSiswaMiScenario(): array
    {
        $admin = User::factory()->admin()->create();

        $ayah = Wali::factory()->create();
        $ibu = Wali::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();

        $siswa = Siswa::factory()->create([
            'tanggal_lahir' => '2000-01-01',
            'jenjang' => 'MI',
            'ayah_id' => $ayah->id,
            'ibu_id' => $ibu->id,
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);

        return compact('admin', 'ayah', 'ibu', 'wali', 'kelas', 'kategori', 'siswa');
    }

    protected function createSiswaTkScenario(): array
    {
        $admin = User::factory()->admin()->create();

        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();

        $siswa = Siswa::factory()->create([
            'jenjang' => 'TK',
            'ayah_id' => null,
            'ibu_id' => null,
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);

        return compact('admin', 'wali', 'kelas', 'kategori', 'siswa');
    }

    protected function createSiswaKbScenario(): array
    {
        $admin = User::factory()->admin()->create();

        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();

        $siswa = Siswa::factory()->create([
            'jenjang' => 'KB',
            'ayah_id' => null,
            'ibu_id' => null,
            'wali_id' => $wali->id,
            'kelas_id' => $kelas->id,
            'kategori_id' => $kategori->id,
        ]);

        return compact('admin', 'wali', 'kelas', 'kategori', 'siswa');
    }

    protected function createPembayaranCicil()
    {
        $user = User::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP',
            'jumlah' => 100000
        ]);
        $siswa = Siswa::factory()
            ->for($wali, 'ayah')
            ->for($wali, 'ibu')
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create([
                'jenjang' => 'MI'
            ]);
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create([
                'tmp' => 150000,
                'status' => 'Lunas'
            ]);
        $pembayaran = Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'jumlah' => 50000,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        $setting = AppSetting::factory()->create();
        return compact('user', 'pembayaran');
    }
    protected function createPembayaranLunas()
    {
        $user = User::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP',
            'jumlah' => 100000
        ]);
        $siswa = Siswa::factory()
            ->for($wali, 'ayah')
            ->for($wali, 'ibu')
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create([
                'jenjang' => 'MI'
            ]);
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create();
        $pembayaran = Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'jumlah' => $jt->jumlah,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        $setting = AppSetting::factory()->create();
        return compact('user', 'pembayaran');
    }
    protected function createTagihan()
    {
        $user = User::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'Pendaftaran',
            'jumlah' => 50000
        ]);
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $wali = Wali::factory()->create();
        $siswa = Siswa::factory()
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create();
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create();
        return compact('user', 'tagihan');
    }
    protected function createKasHarian()
    {
        $user = User::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP',
            'jumlah' => 100000
        ]);
        $siswa = Siswa::factory()
            ->for($wali, 'ayah')
            ->for($wali, 'ibu')
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create([
                'jenjang' => 'MI'
            ]);
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create();
        // Pemasukan & Pengeluaran dalam bulan Januari 2025
        Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'tanggal' => '2025-01-01',
                'jumlah' => $jt->jumlah,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        // Tambahan pemasukan di Januari
        Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'tanggal' => '2025-01-10',
                'jumlah' => 50000,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        // Pemasukan di bulan lain (Februari) — memastikan tidak mempengaruhi saldo Januari
        Pembayaran::factory()
            ->for($tagihan, 'tagihan')
            ->create([
                'tanggal' => '2025-02-01',
                'jumlah' => $jt->jumlah,
                'metode' => 'Tunai',
                'pembayar' => $wali->nama
            ]);
        Pengeluaran::factory()->create([
            'tanggal' => '2025-01-01',
            'jumlah' => 50000,
        ]);
        // Pengeluaran tambahan di Januari
        Pengeluaran::factory()->create([
            'tanggal' => '2025-01-05',
            'jumlah' => 25000,
        ]);
        return compact('user');
    }

    protected function createRekapBulanan()
    {
        $user = User::factory()->create();
        $wali = Wali::factory()->create();
        $kelas = Kelas::factory()->create();
        $kategori = Kategori::factory()->create();
        $jt = JenisTagihan::factory()->create([
            'nama' => 'SPP',
            'jumlah' => 100000
        ]);
        $siswa = Siswa::factory()
            ->for($wali, 'wali')
            ->for($kelas, 'kelas')
            ->for($kategori, 'kategori')
            ->create([
                'jenjang' => 'MI'
            ]);
        $tagihan = Tagihan::factory()
            ->for($siswa, 'siswa')
            ->for($jt, 'jenis_tagihan')
            ->create();

        // Pemasukan Jan & Feb
        Pembayaran::factory()->for($tagihan, 'tagihan')->create([
            'tanggal' => '2025-01-01',
            'jumlah' => 100000,
            'metode' => 'Tunai'
        ]);
        Pembayaran::factory()->for($tagihan, 'tagihan')->create([
            'tanggal' => '2025-02-01',
            'jumlah' => 150000,
            'metode' => 'Tunai'
        ]);

        // Pengeluaran Jan & Feb
        Pengeluaran::factory()->create([
            'tanggal' => '2025-01-15',
            'jumlah' => 40000,
        ]);
        Pengeluaran::factory()->create([
            'tanggal' => '2025-02-10',
            'jumlah' => 50000,
        ]);
        Pengeluaran::factory()->create([
            'tanggal' => '2026-01-01',
            'jumlah' => 10000,
        ]);

        return compact('user');
    }

    protected function createAdminWithToken(): \App\Models\User
    {
        /** @var \App\Models\User $admin */
        $admin = \App\Models\User::factory()->admin()->create();
        $admin->token = \Illuminate\Support\Str::uuid()->toString();
        $admin->save();

        return $admin;
    }

    // --- Wali scenarios & payload builders ---
    protected function createWaliIndexScenario(int $count = 3): array
    {
        $user = \App\Models\User::factory()->create();
        \App\Models\Wali::factory()->count($count)->create();
        return compact('user');
    }

    protected function createWaliSearchScenario(): array
    {
        $user = \App\Models\User::factory()->create();
        \App\Models\Wali::factory()->create(['nama' => 'Budi Santoso']);
        \App\Models\Wali::factory()->create(['nama' => 'Andi Wijaya']);
        return compact('user');
    }

    protected function createWaliForCrud(): array
    {
        $user = \App\Models\User::factory()->create();
        $wali = \App\Models\Wali::factory()->create();
        $siswa = \App\Models\Siswa::factory()->create([
            'wali_id' => $wali->id,
        ]);
        return compact('user', 'wali');
    }

    protected function buildWaliValidPayload(): array
    {
        return [
            'nama' => 'Ayah',
            'jenis_kelamin' => 'Laki-laki',
            'agama' => 'Islam',
            'pendidikan_terakhir' => 'SMA',
            'pekerjaan' => 'Wiraswasta',
            'alamat' => 'Pontianak',
            'no_hp' => '081122334455',
            'keterangan' => null,
        ];
    }

    protected function buildWaliInvalidRequiredPayload(): array
    {
        return [];
    }

    protected function buildWaliInvalidJenisKelaminPayload(): array
    {
        $p = $this->buildWaliValidPayload();
        $p['jenis_kelamin'] = 'Unknown';
        return $p;
    }

    protected function buildWaliInvalidNoHpPayload(): array
    {
        $p = $this->buildWaliValidPayload();
        $p['no_hp'] = 'invalid#phone';
        return $p;
    }
}
